@echo off
g++ -o programa.exe ^
    main.cpp ^
    Fabrica.cpp ^
    CIniciarSesion.cpp ^
    CCerrarSesion.cpp ^
    Sesion.cpp ^
    Usuario.cpp ^
    Sala.cpp ^
    Reserva.cpp ^
    Puntaje.cpp ^
    Pelicula.cpp ^
    ManejadorUsuario.cpp ^
    ManejadorFuncion.cpp ^
    ManejadorCine.cpp ^
    ManejadorPelicula.cpp ^
    Funcion.cpp ^
    DtSala.cpp ^
    DtReserva.cpp ^
    DtPuntaje.cpp ^
    DtPelicula.cpp ^
    DtHorario.cpp ^
    DtFuncion.cpp ^
    DtFecha.cpp ^
    DtDireccion.cpp ^
    DtComentario.cpp ^
    DtCine.cpp ^
    Debito.cpp ^
    Credito.cpp ^
    Controlador.cpp ^
    Comentario.cpp ^
    Cine.cpp ^
    CAltaUsuario.cpp ^
    CAltaFuncion.cpp 